### ISSUE TITLE
runtime and one chromosome test

### ISSUE THREAD

**Issue by LuQiao-spec** [dantaki/SV2#22]
Hi,

1. Could SV2 take a region of SV to genotype like chr21 as input file? I want to test the pipeline on my real data. I get the a VCF of SV from Manta, only including chr21 SVs. Using the following command by SV2: sv2 -i sample.cram -v sample_chr21_diploidSV.vcf.gz -p sample.ped -snv all_samples.vcf.gz -o sample -genome hg38. I get all three steps' result, but some of them are empty or cannot be genotyped ./. : 
1). sample_sv2_preprocessing.txt:
#id     chrom   coverage_median read_length_median      insert_size_median      insert_size_mad bam_bp_parsed   snv_depth_median        snv_parsed
2). sample_sv2_features.txt
#chr    start   end     type    size    id      coverage        coverage_GCcorrected    discordant_ratio        split_ratio     snv_coverage    heterozygous_allele_ratio       snvs    het_snvs
chr21   10769163        10770077        DEL     914     sampleID      nan     nan     0.0     0.0     1.892   0.365   79      14
chr21   18859198        18859269        DEL     71      sampleID      nan     nan     0.0     0.0     1.081   nan     2       0
...
3) #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SampleID
chr21   6565916 MantaDEL:2:3:3:0:3:1    .       <DEL>   NA      SEGDUP;STR;GENOTYPEFAIL END=6566035;SVTYPE=DEL;SVLEN=120;DENOVO_FILTER=NA;REF_GTL=NA;AF=NA;CYTOBAND=21p12;REPEATMASKER=NA,0;1000G_ID=NA;1000G_OVERLAP=NA;DESCRIPTION=chr21:6565916-6566035_deletion;GENES=XM_017028224.1,LOC102724843,UTR5|XM_017028222.1,LOC102724843,UTR5;ABPARTS=0;CENTROMERE=0;GAP=0;SEGDUP=1.0;STR=1.0;UNMAPPABLE=0        GT:CN:PE:SR:SC:NS:HA:NH:SQ:GL   ./.
...
Is this because I use one chromesome SVs as input?

2. I test the above command using 24 hours per person, which is much longer. Even I performed qsub and job-array task by: qsub -tc 10 -t 2-600 command.sh. Actually, I used -snv all_sample.vcf.gz as SNV input. It's a huge file, including 600 samples. Would this snv file be the reason to take such long time? I will do a batch CNV genotyping later. Is there any way to save time?

3. Thanks for your answer about de novo filter before. Does that mean sv2 doesn't consider the real pedigree relationship (in .ped file) to do the de novo filter, but using the training cutoffs (median REF likelihood and median ALF likelihood) to filter de novo SVs?  The DENOVO_FILTER=PASS is determined by all samples, no matter they are children or parents?

Thanks for your patients and looking forward to your answer.

Emma

**Comment by LuQiao-spec** [comment]
4. There are some reports in the -e sample.error file:
WARNING: Skipping bad entry chr21       6070671 MantaINV:58:0:1:0:0:0   C       <INV>   152     MinGQ   END=43468313;SVTYPE=INV;SVLEN=37397642;IMPRECISE;CIPOS=-263,263;CIEND=-223,223;INV3     GT:FT:GQ:PL:PR  1/1:MinGQ:5:204,7,0:2,13 in ./sample_diploidSV.vcf.gz. INV not an accepted SV type. Accepted types: DEL or DUP: https://github.com/dantaki/SV2/wiki/input#sv-input
...
Unable to fetch reference #13 69723194..69754703
Failure to decode slice
Failed to populate reference for id 13
Unable to fetch reference #13 69723194..69754703
Failure to decode slice

sv2 doesn't genotype inversion, which is the reason of Warning. Does the failure to decode slice matter with the empty preprocessing?

**Comment by dantaki** [comment]
The answers to nearly all your questions can be found in the User Guide. Please familiarize yourself with the different options and output that's detailed in the guide. 

https://github.com/dantaki/SV2/wiki

1. Depends on the alignment file and file containing SV calls. If your alignment file has only chr21 then genotypes from any other contig would not work. SV2 will attempt to genotype any SV in the VCF or BED file you provide. 

That SV was unable to be genotyped because

> Before feature extraction, a mask is applied to SV regions. The mask includes segmental duplications, short tandem-repeats, centromeres, telomeres, and unmappable regions and is included here $SV2_INSTALL_DIR/sv2/sv2/resources/annotation_files/*excluded.bed.gz. The genome mask with merged positions is located here $SV2_INSTALL_DIR/sv2/sv2/resources/*_excluded.bed.gz. SV calls that completely overlap masked elements cannot be genotyped and are represented as ./. in the output VCF.

https://github.com/dantaki/SV2/wiki/Introduction#feature-extraction

2. Yes I would recommend splitting the VCF by pedigree or samples. `bcftools` can help you with that. Otherwise I have a version of SV2 that I haven't uploaded yet that forgoes the need for a VCF, but only genotypes deletions.

3. Yes. https://github.com/dantaki/SV2/wiki/performance#de-novo-mutations

4. This error typically means that either the BAM or the SNV VCF does not that the contig in the header files, and fetching would not work.
