### ISSUE TITLE
Question about output

### ISSUE THREAD

**Issue by fritzsedlazeck** [dantaki/SV2#4]
Hi,
I am trying to run your method on multiple files on a cluster. It seems to give me an error about the naming of the output files. 

Is it correct that it always tries to create a folder "sv2_genotypes" and puts the output for each run in there? Is there a way to customize the output folder and name?
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Or do I need to set a combination of -T and -o ?

**Comment by dantaki** [comment]
It is correct that the `sv2_genotypes` folder is created in the working directory for each run. 

If a `sv2_genotypes/` folder is already created, then it does not re-write over any existing data. 

`-o` is the output prefix, so if you were to specify `-o myrun`, sv2 will output two files in `sv2_genotypes/`: `sv2_genotypes/myrun.txt` and `sv2_genotypes/myrun.vcf` 

The `-T` option is for temporary files sv2 creates during annotation and other steps. 

Do you mind sharing what was the error? I can adapt the code so that users can specify the full output paths

**Comment by fritzsedlazeck** [comment]
Hi, 
its not an error, but I would like to specify the path and file name (can be prefix) where all the output should be written. 

I am running it with -o for each sample set having a unique output (including the path) e.g. dup/1000/output_sv2.vc . When we run it it comes back with: Cannot find file "working_directory/sv2_genotypes/dup/1000/output_sv2.vcf"

Where the original  is set to -o dup/1000/output_sv2.vcf. 

Ideally the method would write a result in that file or use that as a prefix for the filenames. 

Does that make sense? Any way I can trigger that behaviour? 
Thanks
Fritz

**Comment by dantaki** [comment]
Makes perfect sense, writing the output to the folder `sv2_genotypes` is a hold over from older versions of SV2 and should be updated. 

I see your problem now, the `-o` flag only accepts the file prefix, not a prefix for a given path. 

I managed to replicate your error by running the tutorial with `-o test/test`, because SV2 expects a file prefix and not sub-folders in `sv2_genotypes` 

You can work-around this error by writing out the files like this `-o dup_1000_output_sv2.vcf`, but I'll have to change the source code to give users more freedom in naming (and placing) output files. It'll be a quick fix, but I'll have to address it in the following weeks due to my current limited bandwidth. 

Thanks for bringing it to my attention!

**Comment by fritzsedlazeck** [comment]
Thanks. I understand your limited time, but I need to run it on 200+ data sets....

So I would appreciate if you find a minute.
Thanks
Fritz

**Comment by dantaki** [comment]
No problem, fixed with v1.4.3 989ecee5efecf05f8f2c13d0922de01f55ac6c32

Users have the choice to supply an output path `-O, -odir` for the SV<sup>2</sup> output directories (`sv2_preprocessing/`, `sv2_features/`, `sv2_genotypes/`) 

```
$ sv2 -i in.bam -snv in.vcf.gz -p in.ped -v sv.vcf -o foo -O /home/bar
```

SV<sup>2</sup> genotypes are now in `/home/bar/sv2_genotypes/foo.vcf` 

Please reinstall SV<sup>2</sup> with pip or using the release tarball https://github.com/dantaki/SV2/releases/tag/sv2v1.4.3

I hope this fixes your issue, just make sure the path given to `-O` exists.

**Comment by fritzsedlazeck** [comment]
Awsome I will give it a try.
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Awsome I will give it a try.
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi,
sorry to open that up again. We are getting an error with the pip install. Maybe you have some suggestions:

```
Collecting sv2
  Using cached sv2-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NdMYAx/sv2/setup.py", line 6, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
```

It went through with the previous version so thats why I figured I just ask you.
Thanks
Fritz

**Comment by dantaki** [comment]
That's odd. Can you try `pip install cython --upgrade` and then install it again? Or maybe use `pip2 install sv2` if your are using pip with python3.

Also try `pip install --no-cache-dir sv2`

**Comment by fritzsedlazeck** [comment]
Thanks that worked and I see the new option. 
Cheers
Fritz

**Comment by dantaki** [comment]
Awesome, I'll leave a note in the Troubleshooting section in the Wiki
